[package]
name = "pyclientinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext" }
clientinfo = { path = "../../../../lib/clientinfo" }
cpython = { version = "0.7", default-features = false }
pyconfigloader = { path = "../pyconfigloader" }
