[package]
name = "pycliparser"
version = "0.1.0"
edition = "2021"

[dependencies]
clidispatch = { path = "../../../../lib/clidispatch" }
cliparser = { path = "../../../../lib/cliparser", features = ["python"] }
configmodel = { path = "../../../../lib/config/model" }
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
pyconfigloader = { path = "../pyconfigloader" }

