[package]
name = "pycats"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext" }
cats = { path = "../../../../lib/cats" }
pyconfigloader = { path = "../pyconfigloader" }
url = "2.1.0"

