[package]
name = "pyrepo"
version = "0.1.0"
edition = "2021"


[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
repo = { path = "../../../../lib/repo" }
util = { path = "../../../../lib/util" }
parking_lot = "0.11.2"
pyconfigloader = { path = "../pyconfigloader" }
pydag = { path = "../pydag" }
pyedenapi = { path = "../pyedenapi" }
pymetalog = { path = "../pymetalog" }
pyworkingcopy = { path = "../pyworkingcopy" }
workingcopy = { path = "../../../../lib/workingcopy" }

