[package]
name = "pyio"
version = "0.1.0"
edition = "2021"

[dependencies]
clidispatch = { path = "../../../../lib/clidispatch", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
pyconfigloader = { path = "../pyconfigloader" }
termstyle = { path = "../../../../lib/io/term/style" }

