[package]
name = "pyconfigloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
configloader = { path = "../../../../lib/config/loader" }
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext" }
util = { path = "../../../../lib/util" }
version = { path = "../../../../lib/version" }
